version: "3.4"
volumes:
  database:
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
    volumes:
      - database:/var/lib/postgresql/data
    expose:
      - 5432
  app:
    image: servermate/auth
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
