spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:servermate}
    username: ${DB_USER:ucode}
    password: ${DB_PASS:secret}
  jpa:
    hibernate:
      ddl-auto: update
