spring:
  datasource:
    url: jdbc:postgresql://database:5432/${DB_NAME:servermate}
    username: ${DB_USER:ucode}
    password: ${DB_PASS:secret}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
